DROP TABLE IF EXISTS ARTICULOS CASCADE
;
DROP TABLE IF EXISTS COMPRA CASCADE
;
DROP TABLE IF EXISTS CLIENTE CASCADE
;

CREATE TABLE ARTICULOS
(
	CodArticulo INTEGER NOT NULL AUTO_INCREMENT,
	DescArticulo VARCHAR(100),
	Precio DECIMAL(10,2),
	Stock INTEGER,
	PRIMARY KEY (CodArticulo)

) 
;


CREATE TABLE COMPRA
(
	IdCompra INTEGER NOT NULL AUTO_INCREMENT,
	FechaVenta DATETIME,
	UnidVendida INTEGER,
	CodCliente INTEGER,
	CodArticulo INTEGER,
	PRIMARY KEY (IdCompra),
	KEY (CodArticulo),
	KEY (CodCliente)

) 
;


CREATE TABLE CLIENTE
(
	CodCliente INTEGER NOT NULL AUTO_INCREMENT,
	NomCliente VARCHAR(80),
	DirCliente VARCHAR(80),
	TelCliente VARCHAR(80),
	PRIMARY KEY (CodCliente)

) 
;





ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_ARTICULOS 
	FOREIGN KEY (CodArticulo) REFERENCES ARTICULOS (CodArticulo)
;

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_CLIENTE 
	FOREIGN KEY (CodCliente) REFERENCES CLIENTE (CodCliente)
;
